api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/DTO'
            - '%kernel.project_dir%/config/kbin_api'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    formats:
        jsonld:   ['application/ld+json']
