fos_elastica:
  clients:
    default: { url: '%env(ELASTICSEARCH_URL)%' }
  indexes:
    magazines:
      settings:
        index:
          analysis:
            analyzer:
              kbin_analyzer:
                type: custom
                tokenizer: standard
                filter: ['lowercase', 'morfologik_stem']
      properties:
        id: ~
        name: {  boost: 30, type: "keyword" }
        title: { boost: 20, analyzer: kbin_analyzer }
        description: { analyzer: kbin_analyzer }
        rules: { analyzer: kbin_analyzer }
        createdAt: { "type": "date" }
        visibility: ~
        cover:
          type: "object"
          properties:
            id: ~
            filePath: ~
        tags:
          property_path: false
      persistence:
        driver: orm
        model: App\Entity\Magazine
        listener: '%elastica_listener%'
    entries:
      settings:
        index:
          analysis:
            analyzer:
              kbin_analyzer:
                type: custom
                tokenizer: standard
                filter: [ 'lowercase', 'morfologik_stem' ]
      properties:
        id: ~
        title: { boost: 20, analyzer: kbin_analyzer }
        url: ~
        body: { boost: 10, analyzer: kbin_analyzer }
        type: ~
        ranking: ~
        score: ~
        isAdult: ~
        sticky: ~
        createdAt: { "type": "date" }
        lastActive: ~
        visibility: ~
        magazine:
          type: "object"
          properties:
            name: ~
        domain:
          type: "object"
          properties:
            id: ~
            name: ~
        user:
          type: "object"
          properties:
            username: { "type": "keyword" }
        image:
          type: "object"
          properties:
            id: ~
            filePath: ~
        tags: ~
      persistence:
        driver: orm
        model: App\Entity\Entry
        listener: '%elastica_listener%'
    entry_comments:
      settings:
        index:
          analysis:
            analyzer:
              kbin_analyzer:
                type: custom
                tokenizer: standard
                filter: [ 'lowercase', 'morfologik_stem' ]
      properties:
        id: ~
        body: { boost: 10, analyzer: kbin_analyzer }
        createdAt: { "type": "date" }
        lastActive: ~
        visibility: ~
        magazine:
          type: "object"
          properties:
            name: { "type": "keyword" }
        entry:
          type: "object"
          properties:
            id: ~
        user:
          type: "object"
          properties:
            username: { "type": "keyword" }
        image:
          type: "object"
          properties:
            id: ~
            filePath: ~
        tags: ~
      persistence:
        driver: orm
        model: App\Entity\EntryComment
        listener: '%elastica_listener%'
    posts:
      settings:
        index:
          analysis:
            analyzer:
              kbin_analyzer:
                type: custom
                tokenizer: standard
                filter: [ 'lowercase', 'morfologik_stem' ]
      properties:
        id: ~
        body: { boost: 10, analyzer: kbin_analyzer }
        ranking: ~
        score: ~
        isAdult: ~
        createdAt: { "type": "date" }
        lastActive: ~
        visibility: ~
        magazine:
          type: "object"
          properties:
            name: { "type": "keyword" }
        user:
          type: "object"
          properties:
            username: { "type": "keyword" }
        image:
          type: "object"
          properties:
            id: ~
            filePath: ~
        tags: ~
      persistence:
        driver: orm
        model: App\Entity\Post
        listener: '%elastica_listener%'
    post_comments:
      settings:
        index:
          analysis:
            analyzer:
              kbin_analyzer:
                type: custom
                tokenizer: standard
                filter: [ 'lowercase', 'morfologik_stem' ]
      properties:
        id: ~
        body: { boost: 10, analyzer: kbin_analyzer }
        createdAt: { "type": "date" }
        lastActive: ~
        visibility: ~
        magazine:
          type: "object"
          properties:
            name: { "type": "keyword" }
        post:
          type: "object"
          properties:
            id: ~
        user:
          type: "object"
          properties:
            username: { "type": "keyword" }
        image:
          type: "object"
          properties:
            id: ~
            filePath: ~
        tags: ~
      persistence:
        driver: orm
        model: App\Entity\PostComment
        listener: '%elastica_listener%'
