# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        default_adapter:
            local:
                location: "%kernel.project_dir%/public/%uploads_dir_name%"

    filesystems:
        public_uploads_filesystem:
            adapter: default_adapter
            alias: League\Flysystem\Filesystem
