cardano_wallet_new:
  controller: App\Controller\Cardano\CardanoWalletCreateController
  path: /cardano/wallet/new
  methods: [ GET, POST ]

cardano_wallet_mnemonic:
  controller: App\Controller\Cardano\CardanoWalletMnemonicController
  path: /cardano/wallet/mnemonic
  methods: [  POST ]

cardano_wallet_detach:
  controller: App\Controller\Cardano\CardanoWalletDetachController
  path: /cardano/wallet/detach
  methods: [ POST ]

cardano_estimate_fee:
  controller: App\Controller\Cardano\CardanoTransactionFeeController
  path: /cardano/estimate_fee
  methods: [ POST ]
