domain_front:
  controller: App\Controller\Domain\FrontController
  defaults: { sortBy: ~, time: ~ }
  path: /d/{name}/{sortBy}/{time}
  methods: [ GET ]
  requirements: { sortBy: "%front_sort_options%" }

domain_entry_comments_front:
  controller: App\Controller\Domain\CommentFrontController
  defaults: { sortBy: ~, time: ~ }
  path:
    en: d/{name}/comments/{sortBy}/{time}
    pl: d/{name}/komentarze/{sortBy}/{time}
  methods: [GET]
  requirements: { sortBy: "%front_sort_options%" }

domain_subscribe:
  controller: App\Controller\Domain\DomainSubController::subscribe
  path: /d/{name}/subscribe
  methods: [ POST ]

domain_unsubscribe:
  controller: App\Controller\Domain\DomainSubController::unsubscribe
  path: /d/{name}/unsubscribe
  methods: [ POST ]

domain_block:
  controller: App\Controller\Domain\DomainBlockController::block
  path: /d/{name}/block
  methods: [ POST ]

domain_unblock:
  controller: App\Controller\Domain\DomainBlockController::unblock
  path: /d/{name}/unblock
  methods: [ POST ]
