front:
  controller: App\Controller\FrontController::front
  defaults: { sortBy: ~, time: ~ }
  path: /{sortBy}/{time}
  methods: [GET]
  requirements: { sortBy: "%front_sort_options%" }

front_subscribed:
  controller: App\Controller\FrontController::subscribed
  defaults: { sortBy: ~, time: ~ }
  path: /sub/{sortBy}/{time}
  methods: [GET]
  requirements: { sortBy: "%front_sort_options%" }

front_moderated:
  controller: App\Controller\FrontController::moderated
  defaults: { sortBy: ~, time: ~ }
  path: /mod/{sortBy}/{time}
  methods: [GET]
  requirements: { sortBy: "%front_sort_options%" }

front_federated:
  controller: App\Controller\FederationController
  defaults: { sortBy: ~, time: ~ }
  path: /fed/{sortBy}/{time}
  methods: [GET]
  requirements: { sortBy: "%front_sort_options%" }

front_magazine:
  controller: App\Controller\FrontController::magazine
  defaults: { sortBy: ~, time: ~ }
  path: /m/{name}/{sortBy}/{time}
  methods: [GET]
  requirements: { sortBy: "%front_sort_options%" }
