user_profile_messages:
  controller: App\Controller\Message\MessageThreadListController
  path:
    en: /profile/messages
    pl: /profil/wiadomości
  methods: [ GET ]

user_profile_message:
  controller: App\Controller\Message\MessageThreadController
  path:
    en: /profile/messages/{id}
    pl: /profil/wiadomości/{id}
  methods: [ GET, POST ]

user_message:
  controller: App\Controller\Message\MessageCreateThreadController
  path:
    en: /u/{username}/message
    pl: /u/{username}/wiadomość
  methods: [ GET, POST ]
