app_register:
  controller: App\Controller\Security\RegisterController
  path:
    en: /register
    pl: /zarejestruj
  methods: [ GET, POST ]

app_verify_email:
  controller: App\Controller\Security\VerifyEmailController
  path:
    en: /verify/email
    pl: /zweryfikuj/email
  methods: [ GET ]

app_login:
  controller: App\Controller\Security\LoginController
  path:
    en: /login
    pl: /zaloguj
  methods: [ GET, POST ]

app_logout:
  controller: App\Controller\SecurityController::logout
  path:
    en: /logout
    pl: /wyloguj
  methods: [ GET ]
