user:
  controller: App\Controller\User\UserFrontController::front
  path: /u/{username}
  methods: [ GET ]

user_entries:
  controller: App\Controller\User\UserFrontController::entries
  path:
    en: /u/{username}/threads
    pl: /u/{username}/treści
  methods: [ GET ]

user_entry_comments:
  controller: App\Controller\User\UserFrontController::comments
  path:
    en: /u/{username}/comments
    pl: /u/{username}/komentarze
  methods: [ GET ]

user_posts:
  controller: App\Controller\User\UserFrontController::posts
  path:
    pl: /u/{username}/wpisy
    en: /u/{username}/posts
  methods: [ GET ]

user_replies:
  controller: App\Controller\User\UserFrontController::replies
  path:
    en: /u/{username}/odpowiedzi
    pl: /u/{username}/replies
  methods: [ GET ]

user_moderated:
  controller: App\Controller\User\UserFrontController::moderated
  path:
    en: /u/{username}/moderated
    pl: /u/{username}/moderowane
  methods: [ GET ]

user_subscriptions:
  controller: App\Controller\User\UserFrontController::subscriptions
  path:
    en: /u/{username}/subscriptions
    pl: /u/{username}/subskrypcje
  methods: [ GET ]

user_followers:
  controller: App\Controller\User\UserFrontController::followers
  path:
    en: /u/{username}/followers
    pl: /u/{username}/obserwujący
  methods: [ GET ]

user_follows:
  controller: App\Controller\User\UserFrontController::follows
  path:
    en: /u/{username}/follows
    pl: /u/{username}/obserwowani
  methods: [ GET ]

user_follow:
  controller: App\Controller\User\UserFollowController::follow
  path: /u/{username}/follow
  methods: [ POST ]

user_unfollow:
  controller: App\Controller\User\UserFollowController::unfollow
  path: /u/{username}/unfollow
  methods: [ POST ]

user_block:
  controller: App\Controller\User\UserBlockController::block
  path: /u/{username}/block
  methods: [ POST ]

user_unblock:
  controller: App\Controller\User\UserBlockController::unblock
  path: /u/{username}/unblock
  methods: [ POST ]

user_purge:
  controller: App\Controller\User\UserDeleteController::purge
  path: /u/{username}/purge
  methods: [ POST ]

user_delete:
  controller: App\Controller\User\UserDeleteController::delete
  path: /u/{username}/delete
  methods: [ POST ]

user_ban:
  controller: App\Controller\User\UserBanController::ban
  path: /u/{username}/ban
  methods: [ POST ]

user_unban:
  controller: App\Controller\User\UserBanController::unban
  path: /u/{username}/unban
  methods: [ POST ]

user_note:
  controller: App\Controller\User\UserNoteController
  path: /u/{username}/note
  methods: [ POST ]

user_profile_front:
  controller: App\Controller\User\Profile\UserStatController
  path:
    en: /profile
    pl: /profil
  methods: [ GET ]

user_profile_notifications:
  controller: App\Controller\User\Profile\UserNotificationController::notifications
  path:
    en: /profile/notifications
    pl: /profil/notyfikacje
  methods: [ GET ]

user_profile_notifications_read:
  controller: App\Controller\User\Profile\UserNotificationController::read
  path: /profile/notifications/read
  methods: [ POST ]

user_profile_reports:
  controller: App\Controller\User\Profile\UserReportsController
  path:
    en: /profile/reports
    pl: /profil/zgłoszenia
  methods: [ GET ]

user_profile_notifications_clear:
  controller: App\Controller\User\Profile\UserNotificationController::clear
  path: /profile/notifications/clear
  methods: [ POST ]

user_profile_magazine_blocks:
  controller: App\Controller\User\Profile\UserBlockController::magazines
  path:
    en: /profile/blocklist/magazines
    pl: /profil/blokady/magazyny
  methods: [ GET ]

user_profile_domain_blocks:
  controller: App\Controller\User\Profile\UserBlockController::domains
  path:
    en: /profile/blocklist/domains
    pl: /profil/blokady/domeny
  methods: [ GET ]

user_profile_user_blocks:
  controller: App\Controller\User\Profile\UserBlockController::users
  path:
    en: /profile/blocklist/people
    pl: /profil/blokady/ludzie
  methods: [ GET ]

user_profile_magazine_subscriptions:
  controller: App\Controller\User\Profile\UserSubController::magazines
  path:
    en: /profile/subscriptions/magazines
    pl: /profil/subskrypcje/magazyny
  methods: [ GET ]

user_profile_domain_subscriptions:
  controller: App\Controller\User\Profile\UserSubController::domains
  path:
    en: /profile/subscriptions/domains
    pl: /profil/subskrypcje/domeny
  methods: [ GET ]

user_profile_user_subscriptions:
  controller: App\Controller\User\Profile\UserSubController::users
  path:
    en: /profile/subscriptions/people
    pl: /profil/subskrypcje/ludzie
  methods: [ GET ]

user_profile_tips:
  controller: App\Controller\User\Profile\UserTipController
  path:
    en: /profile/ada
    pl: /profil/ada
  methods: [ GET, POST ]

user_profile_settings:
  controller: App\Controller\User\Profile\UserSettingController
  path:
    en: /profile/settings
    pl: /profil/ustawienia
  methods: [ GET, POST ]

user_profile_edit:
  controller: App\Controller\User\UserEditController
  path:
    en: /profile/edit
    pl: /profil/edytuj
  methods: [ GET, POST ]

user_profile_toggle_theme:
  controller: App\Controller\User\UserThemeController
  path:
    en: /profile/edit/theme
    pl: /profil/edytuj/wyglad
  methods: [ GET, POST ]
