resources:
  App\DTO\EntryCommentDto:
    properties:
      id:
        identifier: true
    shortName: 'entry_comment'
    collectionOperations:
      get:
        method: GET
        normalization_context:
          groups: [ 'entry:comment:collection:get']
      post:
        method: POST
    itemOperations:
      get:
        method: GET
        normalization_context:
          groups: [ 'entry:comment:item:get' ]
    attributes:
      denormalization_context:
        groups: [ 'entry:comment:write' ]
