resources:
  App\DTO\EntryDto:
    properties:
      id:
        identifier: true
#      comments:
#        subresource:
#          resourceClass: 'App\DTO\EntryCommentDto'
#          collection: true
    shortName: 'entry'
    collectionOperations:
      get:
        method: GET
        normalization_context:
          groups: [ 'entry:collection:get' ]
      post:
        method: POST
      comments:
        method: GET
        path: /entries/{id}/comments.{_format}
        controller: App\Controller\Api\EntryComments
        normalization_context:
          groups: [ 'single:entry:comment:collection:get' ]
    itemOperations:
      get:
        method: GET
        normalization_context:
          groups: [ 'entry:item:get' ]
    attributes:
      denormalization_context:
        groups: [ 'entry:write' ]
