resources:
  App\DTO\PostDto:
    properties:
      id:
        identifier: true
    shortName: 'post'
    collectionOperations:
      get:
        method: GET
        normalization_context:
          groups: [ 'post:collection:get' ]
      post:
        method: POST
      comments:
        method: GET
        path: /posts/{id}/comments.{_format}
        controller: App\Controller\Api\PostComments
        normalization_context:
          groups: [ 'single:post:comment:collection:get' ]
    itemOperations:
      get:
        method: GET
        normalization_context:
          groups: [ 'post:item:get' ]
    attributes:
      denormalization_context:
        groups: [ 'post:write' ]
