resources:
  App\DTO\PostCommentDto:
    properties:
      id:
        identifier: true
    shortName: 'post_comment'
    collectionOperations:
      get:
        method: GET
        normalization_context:
          groups: [ 'post:comment:collection:get' ]
      post:
        method: POST
    itemOperations:
      get:
        method: GET
    attributes:
      normalization_context:
        groups: [ 'post:comment:item:get' ]
      denormalization_context:
        groups: [ 'post:comment:write' ]
